spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://ep-raspy-rice-a1ig6dmo.ap-southeast-1.aws.neon.tech/demo?user=neondb_owner&password=0ZEgo3qXkzdG&sslmode=require
    username: postgres
    password: secret99

  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create